### ISSUE TITLE
NoMethodError: undefined method `helper_method'

### ISSUE THREAD

**Issue by Rodeoclash** [hashrocket/decent_exposure#163]
Just dropped decent exposure into a Rails 5.0.01 project. Added a simple `expose :client` in the top of a controller and it blew up with:

```
NoMethodError: undefined method `helper_method' for Api::V1::Clients::TagCategoriesController:Class
```

Could it be the namespaced controllers? I checked the documentation / issues, tried adding: 

```
expose(:client, model: ::Client)
```

Without any luck.  I've used this gem perviously with Rails 4 + nested controller namespaces without issue.

**Comment by vnegrisolo** [comment]
@Rodeoclash I created a PR that will probably solve the problem, so let us know if this works with your app

**Comment by Rodeoclash** [comment]
👌 

Fixed perfectly

**Comment by gthorsen** [comment]
This still occurs for me.  If I pass in current_client into any of the expose method param blocks, I still receive the same helper_method error that Rodeoclash:  

ActionController::RoutingError (undefined method `helper_method' for KnowledgeBase::ContentsController:Class):

Im on Rails API 5.0.0.1 that was upgraded from a Rails 4 API project.  Also using Mongoid, although I don't think that would be related.

**Comment by vnegrisolo** [comment]
@gthorsen are you using the `master` branch version of the gem? This fix was not released in any new version of the gem yet.

It should be something like:

```ruby
gem 'decent_exposure', github: 'hashrocket/decent_exposure', branch: 'master'
```

**Comment by gthorsen** [comment]
@vnegrisolo ahhh I am not, thanks for that, I thought it was.  Cheers.
